package com.mz.sqlite.dal.dao;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public class TableColumnDescriptionJavaSQLiteTableCreateDAO {
	private Connection _connection;

	public TableColumnDescriptionJavaSQLiteTableCreateDAO(Connection SQLiteDatabaseConnection)
	{
		_connection = SQLiteDatabaseConnection;
	}
	

	public void CreateTable()
	{
		Statement stmt;
		try {
			stmt = _connection.createStatement();
			String sql = "CREATE TABLE IF NOT EXISTS " + TableColumnDescriptionTableDescription.TABLE_NAME + " " +
	                
				"(" + TableColumnDescriptionTableDescription.NameStr_COLUMN + " STRING  ," +
				"" + TableColumnDescriptionTableDescription.TypeStr_COLUMN + " STRING  ," +
				"" + TableColumnDescriptionTableDescription.PrimaryKey_COLUMN + " BOOLEAN  ," +
				"" + TableColumnDescriptionTableDescription.AutoGeneratedValueBln_COLUMN + " BOOLEAN  ," +
				"" + TableColumnDescriptionTableDescription.NotNull_COLUMN + " BOOLEAN  ," +
				"" + TableColumnDescriptionTableDescription.Id_COLUMN + " INTEGER PRIMARY KEY AUTOINCREMENT," +
				"" + TableColumnDescriptionTableDescription.IdTableDescription_COLUMN + " STRING  )" ;
			stmt.executeUpdate(sql);
			stmt.close();
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}
