package com.mz.sqlite.dal.dao;

public class TableColumnDescriptionTableRecordPOJO {
	
	

	private String _NameStrString ;
	
	public String getNameStrString(){
		return _NameStrString ;
	}
	
	
	public void setNameStrString(String value){
		_NameStrString = value;
	}

	private String _TypeStrString ;
	
	public String getTypeStrString(){
		return _TypeStrString ;
	}
	
	
	public void setTypeStrString(String value){
		_TypeStrString = value;
	}

	private boolean _PrimaryKeyBoolean ;
	
	public boolean getPrimaryKeyBoolean(){
		return _PrimaryKeyBoolean ;
	}
	
	
	public void setPrimaryKeyBoolean(boolean value){
		_PrimaryKeyBoolean = value;
	}

	private boolean _AutoGeneratedValueBlnBoolean ;
	
	public boolean getAutoGeneratedValueBlnBoolean(){
		return _AutoGeneratedValueBlnBoolean ;
	}
	
	
	public void setAutoGeneratedValueBlnBoolean(boolean value){
		_AutoGeneratedValueBlnBoolean = value;
	}

	private boolean _NotNullBoolean ;
	
	public boolean getNotNullBoolean(){
		return _NotNullBoolean ;
	}
	
	
	public void setNotNullBoolean(boolean value){
		_NotNullBoolean = value;
	}

	private int _IdInt ;
	
	public int getIdInt(){
		return _IdInt ;
	}
	
	
	public void setIdInt(int value){
		_IdInt = value;
	}

	private int _IdTableDescriptionInt ;
	
	public int  getIdTableDescriptionInt(){
		return _IdTableDescriptionInt ;
	}
	
	
	public void setIdTableDescriptionInt(int value){
		_IdTableDescriptionInt = value;
	}

}
