package com.sqlite.dal.test.project.dao;

public class TableColumnDescriptionTableDescription {

	public final static String TABLE_NAME = "TableColumnDescription";
	
	public final static String NameStr_COLUMN = "NameStr";
	
	public final static String TypeStr_COLUMN = "TypeStr";
	
	public final static String PrimaryKey_COLUMN = "PrimaryKey";
	
	public final static String AutoGeneratedValueBln_COLUMN = "AutoGeneratedValueBln";
	
	public final static String NotNull_COLUMN = "NotNull";
	
	public final static String Id_COLUMN = "Id";
	
	public final static String IdTableDescription_COLUMN = "IdTableDescription";
	
	
}
