package com.mz.database.template.context.handlers.column;

import com.mz.database.models.TableColumnDescriptionPOJO;

public class IsColumnAutoGeneratedValueColumnContextHandler extends AbstractColumnTemplateContextHandler {

	public final static String START_CONTEXT_WORD = "{:TDB:TABLE:COLUMN:FOREACH:CURRENT:IS:KEY:AUTO(";
	public final static String END_CONTEXT_WORD = ")KEY:AUTO:::}";
	
	
	@Override
	public String getStartContextStringWrapper() {
		return START_CONTEXT_WORD;
	}

	@Override
	public String getEndContextStringWrapper() {
		return END_CONTEXT_WORD;
	}

	@Override
	public String processContext(String StringContext) throws Exception {
		if(StringContext == null)
			throw new Exception("The provided StringContext is null");
		TableColumnDescriptionPOJO descriptionPojo = getAssociatedColumnDescriptorPOJO();
		if(descriptionPojo == null) 
			throw new Exception("The AssociatedColumnDescriptorPOJO is not set");
		
		String TrimedStringContext = TrimContextFromContextWrapper(StringContext);
		if(descriptionPojo.is_AutoGeneratedValueBln())
		{
			return  HandleTrimedContext(TrimedStringContext);
		}
		else return "";
	}
	
	@Override
	public boolean isStartContextAndEndContextAnEntireWord() {
		return false;
	}

}
