package com.mz.database.models;

import java.io.Serializable;

public class TableColumnDescriptionPOJO implements Serializable {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = 3260743632772068276L;
	public TableColumnDescriptionPOJO(String NameStr,
			String TypeStr,boolean IsPrimaryKey)
	{
		_NameStr = NameStr;
		_TypeStr = TypeStr;
		_PrimaryKey = IsPrimaryKey;
	}

	private String _NameStr;
	public String get_NameStr() {
		return _NameStr;
	}

	public void set_NameStr(String _NameStr) {
		this._NameStr = _NameStr;
	}
	
	private String _TypeStr;
	public String get_TypeStr() {
		return _TypeStr;
	}

	public void set_TypeStr(String _TypeStr) {
		this._TypeStr = _TypeStr;
	}
	

	private boolean _PrimaryKey;
	public boolean is_PrimaryKey() {
		return _PrimaryKey;
	}

	public void set_PrimaryKey(boolean _PrimaryKey) {
		this._PrimaryKey = _PrimaryKey;
	}
	
	private boolean _AutoGeneratedValueBln;
	public boolean is_AutoGeneratedValueBln() {
		return _AutoGeneratedValueBln;
	}

	public void set_AutoGeneratedValueBln(boolean value) {
		this._AutoGeneratedValueBln = value;
	}
	
	private boolean _NotNull;
	public boolean is_NotNull() {
		return _NotNull;
	}

	public void set_NotNull(boolean _NotNull) {
		this._NotNull = _NotNull;
	}
	
//	private int _ColumnIndex;
//	public int get_ColumnIndex() {
//		return _ColumnIndex;
//	}
//
//	public void set_ColumnIndex(int _ColumnIndex) {
//		this._ColumnIndex = _ColumnIndex;
//	}
	
	
	//Template Handler specific properties
	public transient TableDescriptionPOJO ParentTable;
	
}
